name: flutter_forge
description: A command line tool for setting up Flutter projects dynamically.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.19.4
  # sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0

executables:
  flutter_forge: bin/flutter_forge.dart
