name: flutter_forge
description: A command line tool for setting up Flutter projects dynamically.
version: 0.0.1
environment:
  sdk: ^2.19.4
dependencies:
  args: ^2.4.2
dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
executables:
  flutter_forge: flutter_forge
